[package]
name = "elixirrustler_rustmodule"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "elixirrustler_rustmodule"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.31.0"
